---
- hosts: all
  vars_files:
    - "../config.yml"
  tasks:
    - set_fact:
        document_root: "{{ box.share.guest }}/{{app.web_dir}}"

    - name: add php ppa
      become: true
      apt_repository: 
        repo: "ppa:ondrej/php"

    - name: install packages
      apt: 
        name: "{{ item }}"
        state: latest
        update_cache: yes
      become: true
      with_items:
        - acl
        - apache2
        - curl
        - git
        - php
        - php-cli
        - php-curl
        - php-gd
        - php-intl
        - php-xdebug
        - php-xml

    - name: enable apache rewrite module
      become: true
      apache2_module: 
        state: present 
        name: rewrite
      notify:
        - restart apache

    - name: remove apache default config
      file: 
        path: "{{ item }}"
        state: absent
      become: true
      with_items:
        - "/etc/apache2/sites-enabled/000-default.conf"
        - "/etc/apache2/sites-enabled/default"
      notify:
        - restart apache

    - name: install vhost template
      become: true
      template: 
        src: simple_vhost.conf.j2 
        dest: /etc/apache2/sites-enabled/{{ hostname }}.conf
      notify:
        - restart apache

    - name: php.ini settings
      become: true
      lineinfile: 
        dest: "{{ item[1] }}"
        line: "{{ item[0] }}"
      with_nested:
        - 
          - "date.timezone={{ app.php_timezone }}"
          - "xdebug.max_nesting_level=256"
          - "xdebug.remote_enable = 1"
          - "xdebug.remote_connect_back=1"
          - "xdebug.remote_port = 9000"
          - "xdebug.scream=0"
          - "xdebug.show_local_vars=1"
          - "xdebug.idekey=PHPSTORM"
        - 
          - '/etc/php/7.0/apache2/php.ini'
          - '/etc/php/7.0/cli/php.ini'
      notify:
        - restart apache

    - name: install composer
      become: true
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer

    - name: install symfony installer
      become: true
      get_url:
        url: https://symfony.com/installer
        dest: /usr/local/bin/symfony
        mode: 0755

    - name: enable apache service
      become: true
      service: 
        name: apache2
        state: started
        enabled: true

  handlers:
    - name: restart apache
      become: true
      service: 
        name: apache2 
        state: restarted

